### PR TITLE
[WIP] minor documentation updates and misc other things

### PR DESCRIPTION
**Pull request by ctb**
Just walking through the docs, giving it a try... 🚶‍♂️ 

This PR:
- updates deps to spacegraphcats 2.1, just released

I haz questions:
* does it really need 200 GB to run?

### CODE REVIEW

**Comment by taylorreiter** [comment]
> does it really need 200 GB to run? 

no. that param limits the overall mem that can be submitted in parallel to slurm by snakemake. so if `-j` is high, all of the jobs submitted at once won't exceed 200gb

**Comment by ctb** [comment]
thanks!

update: it all ran for me 🎉 , but I haven't had a chance to look at the output. I'll put this up for merge when I get a chance to double check that it all finished without error.

**Comment by taylorreiter** [comment]
well that's super exciting! thanks for the update!

**Review by taylorreiter — APPROVED** [review]
lgtm :)

**Pull request merged**
