### PR TITLE
[MRG] proofreading README

### PR DESCRIPTION
**Pull request by ccbaumler**
Adjusted some sentences in `README.md` and corrected some typos.

### CODE REVIEW

**Comment by ccbaumler** [comment]
Could also adjust runtime estimates and how this may be sped up...

**Comment by taylorreiter** [comment]
Thanks @ccbaumler! after a review? is this ready for merge? If so, would you be willing to add [MRG] into the title? if not, would you prepend the title with [WIP]?

**Comment by ccbaumler** [comment]
Of course! I forgot about that. Thanks for reminding me.

**Review by taylorreiter — APPROVED** [review]
lgtm

**Pull request merged**
